dist: xenial
language: shell

cache:
  directories:
    - "$HOME/.cargo"
    - target
before_cache:
  - curl -sSL "https://github.com/lzutao/cargo-cache/releases/download/0.3.3/cargo-cache-0.3.3-${TRAVIS_OS_NAME}.tar.gz" | tar -xzf - -C ~/.cargo/bin
  - cargo cache --autoclean

git:
  depth: 1
  quiet: true

before_install:
  - curl -sSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=stable --profile=minimal -c rustfmt
  - export PATH="$HOME/.cargo/bin:$PATH"
  - cargo fmt -- --check

install:
  - sudo apt-get update -qq && sudo apt-get install -q libssl-dev

script:
  - cargo fetch
  - cargo check --all --all-targets
