dist: xenial
language: shell

cache:
  directories:
    - "$HOME/.cargo"
    - target
before_cache:
  - cargo install --debug cargo-cache
  - cargo cache --autoclean

git:
  depth: 1
  quiet: true

before_install:
  - curl -sSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=stable --profile=minimal -c rustfmt
  - export PATH="$HOME/.cargo/bin:$PATH"
  - cargo fmt -- --check

script:
  - cargo check
  - cargo check --all --all-targets
